In [1]:
import os
import sys
import pandas as pd
sys.path.append(os.path.dirname(os.getcwd())) #Add project dir to path
from utils.fileProcessing import getJoints3DFromFile, convertJoints3DToDataframe

In [2]:
fulldatasetpath = '/Volumes/Data_Drive/datasets/VIDIMU'

In [3]:
subjects = ["S40","S41","S42",  "S44",  "S46","S47","S48","S49",
            "S50","S51","S52","S53","S54","S55","S56","S57"]

dpath = os.path.join(fulldatasetpath,'dataset','videoandimus')

In [4]:
jointlist3D=["pelvis","left_hip","right_hip","torso","left_knee","right_knee","neck","left_ankle","right_ankle","left_big_toe","right_big_toe",
             "left_small_toe","right_small_toe","left_heel","right_heel","nose","left_eye","right_eye","left_ear","right_ear","left_shoulder",
             "right_shoulder","left_elbow","right_elbow","left_wrist","right_wrist","left_pinky_knuckle","right_pinky_knuckle","left_middle_tip",
             "right_middle_tip","left_index_knuckle","right_index_knuckle","left_thumb_tip"," right_thumb_tip"]

In [5]:
# Check if the path exists
if os.path.exists(dpath):
    print(f"The path exists: {dpath}")
else:
    print(f"The path does not exist: {dpath}")

files = os.listdir(dpath)
files

The path exists: /Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus

['S40',
 'S41',
 'S42',
 'S44',
 'S46',
 'S47',
 'S48',
 'S49',
 'S50',
 'S51',
 'S52',
 'S53',
 'S54',
 'S55',
 'S56',
 'S57']

In [6]:
csv_path = os.path.join(dpath, 'S40', 'S40_A02_T01.csv')
print(csv_path)

df_csv02 = pd.read_csv(csv_path)
print(f'Length: {len(df_csv02)}')
df_csv02.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A02_T01.csv
Length: 1116

,pelvis_x,pelvis_y,pelvis_z,left_hip_x,left_hip_y,left_hip_z,right_hip_x,right_hip_y,right_hip_z,torso_x,...,left_index_knuckle_z,right_index_knuckle_x,right_index_knuckle_y,right_index_knuckle_z,left_thumb_tip_x,left_thumb_tip_y,left_thumb_tip_z,right_thumb_tip_x,right_thumb_tip_y,right_thumb_tip_z
0,1434.0,214.9,6528.5,1432.1,202.9,6602.1,1435.6,205.6,6453.3,1456.7,...,6762.0,1490.1,308.1,6261.4,1566.4,276.9,6750.4,1499.0,327.7,6270.9
1,1445.2,190.8,6582.0,1436.1,177.2,6655.9,1447.5,181.7,6506.6,1468.8,...,6815.8,1503.6,308.3,6317.4,1570.4,277.0,6804.0,1512.5,327.2,6326.9
2,1446.4,170.0,6591.3,1429.4,155.0,6665.1,1449.7,161.2,6516.3,1471.0,...,6823.7,1506.9,306.0,6331.1,1560.7,275.3,6811.8,1515.9,323.7,6340.6
3,1441.8,158.8,6574.3,1419.2,143.0,6647.7,1446.0,150.0,6499.8,1467.4,...,6804.2,1504.0,303.0,6319.0,1547.0,273.8,6792.3,1512.9,319.8,6328.5
4,1436.9,153.1,6556.1,1411.3,136.7,6629.2,1442.1,144.1,6482.0,1463.4,...,6784.1,1500.8,300.7,6304.8,1533.3,272.6,6772.1,1509.6,317.1,6314.3

In [7]:
csv_path = os.path.join(dpath, 'S40', 'S40_A02_T01_Npose.csv')
print(csv_path)

df_npose02 = pd.read_csv(csv_path)
print(f'Length: {len(df_npose02)}')
df_npose02.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A02_T01_Npose.csv
Length: 14

,pelvis_x,pelvis_y,pelvis_z,left_hip_x,left_hip_y,left_hip_z,right_hip_x,right_hip_y,right_hip_z,torso_x,...,left_index_knuckle_z,right_index_knuckle_x,right_index_knuckle_y,right_index_knuckle_z,left_thumb_tip_x,left_thumb_tip_y,left_thumb_tip_z,right_thumb_tip_x,right_thumb_tip_y,right_thumb_tip_z
0,-308.4,166.1,4403.0,-208.2,160.7,4402.0,-406.7,155.4,4404.7,-304.5,...,4267.5,-517.5,262.3,4223.7,-125.6,290.6,4261.9,-490.4,284.4,4215.8
1,-310.9,160.3,4438.2,-209.6,153.2,4436.6,-410.4,147.8,4440.0,-307.1,...,4299.2,-522.3,265.2,4264.7,-128.9,292.5,4294.6,-493.4,287.6,4257.1
2,-312.9,154.0,4466.5,-210.7,145.2,4464.4,-413.7,139.9,4468.5,-309.2,...,4324.3,-526.2,267.8,4298.4,-132.8,293.8,4320.7,-494.9,290.3,4291.2
3,-314.2,149.6,4484.5,-211.2,139.9,4481.9,-415.9,134.7,4486.4,-310.6,...,4341.0,-528.8,269.8,4322.3,-136.0,294.5,4338.3,-495.4,292.4,4315.5
4,-315.2,146.2,4498.7,-211.6,136.1,4495.7,-417.7,130.9,4500.7,-311.8,...,4353.3,-530.8,271.3,4341.7,-139.2,294.8,4351.3,-495.8,293.9,4335.4

In [14]:
for j in list(df_npose02.columns):
    print(j)

pelvis_x
pelvis_y
pelvis_z
left_hip_x
left_hip_y
left_hip_z
right_hip_x
right_hip_y
right_hip_z
torso_x
torso_y
torso_z
left_knee_x
left_knee_y
left_knee_z
right_knee_x
right_knee_y
right_knee_z
neck_x
neck_y
neck_z
left_ankle_x
left_ankle_y
left_ankle_z
right_ankle_x
right_ankle_y
right_ankle_z
left_big_toe_x
left_big_toe_y
left_big_toe_z
right_big_toe_x
right_big_toe_y
right_big_toe_z
left_small_toe_x
left_small_toe_y
left_small_toe_z
right_small_toe_x
right_small_toe_y
right_small_toe_z
left_heel_x
left_heel_y
left_heel_z
right_heel_x
right_heel_y
right_heel_z
nose_x
nose_y
nose_z
left_eye_x
left_eye_y
left_eye_z
right_eye_x
right_eye_y
right_eye_z
left_ear_x
left_ear_y
left_ear_z
right_ear_x
right_ear_y
right_ear_z
left_shoulder_x
left_shoulder_y
left_shoulder_z
right_shoulder_x
right_shoulder_y
right_shoulder_z
left_elbow_x
left_elbow_y
left_elbow_z
right_elbow_x
right_elbow_y
right_elbow_z
left_wrist_x
left_wrist_y
left_wrist_z
right_wrist_x
right_wrist_y
right_wrist_z
left_pinky_knuckle_x
left_pinky_knuckle_y
left_pinky_knuckle_z
right_pinky_knuckle_x
right_pinky_knuckle_y
right_pinky_knuckle_z
left_middle_tip_x
left_middle_tip_y
left_middle_tip_z
right_middle_tip_x
right_middle_tip_y
right_middle_tip_z
left_index_knuckle_x
left_index_knuckle_y
left_index_knuckle_z
right_index_knuckle_x
right_index_knuckle_y
right_index_knuckle_z
left_thumb_tip_x
left_thumb_tip_y
left_thumb_tip_z
 right_thumb_tip_x
 right_thumb_tip_y
 right_thumb_tip_z

In [8]:
csv_path = os.path.join(dpath, 'S40', 'S40_A02_T01.raw')
print(csv_path)

df_raw02 = pd.read_csv(csv_path)
print(f'Length: {len(df_raw02)}')
print(f'Length / numimus: {len(df_raw02)/5}')
df_raw02.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A02_T01.raw
Length: 72670
Length / numimus: 14534.0

     QUAT       w       x       y       z  timestamp
0  qsHIPS  0.7083 -0.0254 -0.7053 -0.0195        0.0
1   qsRUL  0.3997  0.5901 -0.5221  0.4684        0.0
2   qsRLL  0.4661  0.5715 -0.4908  0.4639        0.0
3   qsLUL  0.4182 -0.6013 -0.4916 -0.4711        0.0
4   qsLLL  0.4445 -0.6266 -0.4552 -0.4500        0.0

In [9]:
csv_path = os.path.join(dpath, 'S40', 'S40_A02_T01.sto')

# Open the file and skip the header (everything before 'endheader')
with open(csv_path, 'r') as file:
    # Read all lines
    lines = file.readlines()

# Find the line where the data starts (after 'endheader')
for i, line in enumerate(lines):
    if 'endheader' in line:
        start_idx = i + 1  # Data starts after the 'endheader'
        break

# Now read the data from the relevant lines and load it into a pandas DataFrame
from io import StringIO

# Join the data lines into a single string for pandas to read
data = ''.join(lines[start_idx:])

# Use StringIO to treat the string as a file and read it with pandas
df_sto02 = pd.read_csv(StringIO(data), sep='\s+')

# Display the DataFrame
print(f'Length: {len(df_sto02)}')
df_sto02.head()

Length: 1865

,time,pelvis_imu,femur_r_imu,tibia_r_imu,femur_l_imu,tibia_l_imu
0,0.00,"0.7082424965848898,-0.025397937898145134,-0.70...","0.3997069809433838,0.5901103063665017,-0.52210...","0.4661118137536313,0.5715144852181941,-0.49081...","0.41818772637034396,-0.601282352621922,-0.4915...","0.4445189257961572,-0.6266266791988124,-0.4552..."
1,0.02,"0.520284043133092,0.4671856716351731,-0.512984...","0.018299127152451748,-0.7550639843069024,-0.02...","0.0030999856780992508,-0.7478965447259451,0.06...","0.6561942583253593,-0.07109937788316525,-0.751...","0.6389211166918658,-0.05270174182135127,-0.766..."
2,0.04,"0.5204079649048547,0.46710714912962653,-0.5129...","0.018199384507223776,-0.754974467195272,-0.020...","0.003300019420671436,-0.7477044002533433,0.062...","0.6560931963488306,-0.07099926374145248,-0.751...","0.6388564506400892,-0.052996387359406365,-0.76..."
3,0.06,"0.520703600677848,0.46700322933849636,-0.51280...","0.018199565945528236,-0.7548819962790806,-0.02...","0.0033998023072435834,-0.7475565308515597,0.06...","0.6558914898631281,-0.07079908138787844,-0.751...","0.6386857255335497,-0.053098813254785486,-0.76..."
4,0.08,"0.5208047836139064,0.4671042903726107,-0.51270...","0.018199747025274514,-0.7547895084987474,-0.02...","0.003599788158700107,-0.7475560076233889,0.062...","0.6556891713827512,-0.07059883406988293,-0.751...","0.6385019282787351,-0.05350016157073192,-0.766..."

In [10]:
csv_path = os.path.join(dpath, 'S40', 'ik_S40_A01_T01_orientationErrors.sto')

data = []
columns = []
metadata_section = True  # Flag to skip metadata

with open(csv_path, 'r') as file:
    for line in file:
        line = line.strip()
        # Skip metadata section
        if metadata_section:
            if "endheader" in line:  # When the metadata ends
                metadata_section = False  # Switch to data reading mode
            continue
        
        # If we reach here, we're in the data section
        if line.startswith("time"):
            columns = line.split()  # Set column names when 'time' line appears
        else:
            data.append(line.split())  # Append numeric data

# Convert the data to a DataFrame
df = pd.DataFrame(data, columns=columns)

# Convert the values to appropriate data types
df_oerr02 = df.apply(pd.to_numeric)

# Display the first few rows
df_oerr02.head()

   time    pelvis_imu   femur_r_imu   tibia_r_imu   femur_l_imu   tibia_l_imu
0  0.00  6.139789e-16  1.430490e-17  1.218265e-16  1.816165e-16  1.851528e-16
1  0.02  1.566312e-04  1.918315e-02  7.594495e-02  2.087194e-02  8.321352e-02
2  0.04  1.335284e-04  1.909792e-02  7.603534e-02  2.090586e-02  8.363318e-02
3  0.06  1.228591e-04  1.903972e-02  7.615453e-02  2.094129e-02  8.376189e-02
4  0.08  4.650858e-05  1.913853e-02  7.560844e-02  2.095299e-02  8.420142e-02

In [11]:
# Define the file path
csv_path = os.path.join(dpath, 'S40', 'ik_S40_A02_T01.mot')
print(csv_path)

# Open the file and skip the header (everything before 'endheader')
with open(csv_path, 'r') as file:
    # Read all lines
    lines = file.readlines()

# Find the line where the data starts (after 'endheader')
for i, line in enumerate(lines):
    if 'endheader' in line:
        start_idx = i + 1  # Data starts after the 'endheader'
        break

# Now read the data from the relevant lines and load it into a pandas DataFrame
from io import StringIO

# Join the data lines into a single string for pandas to read
data = ''.join(lines[start_idx:])

# Use StringIO to treat the string as a file and read it with pandas
df_mot02 = pd.read_csv(StringIO(data), sep='\s+')

# Display the DataFrame
print(f'Length: {len(df_mot02)}')
df_mot02.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/ik_S40_A02_T01.mot
Length: 1865

,time,pelvis_tilt,pelvis_list,pelvis_rotation,pelvis_tx,pelvis_ty,pelvis_tz,hip_flexion_r,hip_adduction_r,hip_rotation_r,...,pro_sup_r,wrist_flex_r,wrist_dev_r,arm_flex_l,arm_add_l,arm_rot_l,elbow_flex_l,pro_sup_l,wrist_flex_l,wrist_dev_l
0,0.00,0.000000,0.000000,0.000000,0,0.94,0,0.000000,0.000000,0.000000,...,90.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,90.000000,0,0.0
1,0.02,0.793786,-1.966724,89.740813,0,0.94,0,1.413670,-3.923510,-4.895766,...,89.674155,0,0.0,1.828323,-1.828323,0.325845,9.111087,89.674155,0,0.0
2,0.04,0.802144,-1.964312,89.737013,0,0.94,0,1.420787,-3.923891,-4.900815,...,89.674061,0,0.0,1.828826,-1.828826,0.325939,9.114137,89.674061,0,0.0
3,0.06,0.794658,-1.980499,89.717127,0,0.94,0,1.430931,-3.940055,-4.888690,...,89.673854,0,0.0,1.829894,-1.829894,0.326146,9.122819,89.673854,0,0.0
4,0.08,0.741252,-2.008496,89.707798,0,0.94,0,1.475868,-4.013878,-4.871714,...,89.673049,0,0.0,1.834054,-1.834054,0.326951,9.155096,89.673049,0,0.0

In [12]:
print(df_mot02.columns)

Index(['time', 'pelvis_tilt', 'pelvis_list', 'pelvis_rotation', 'pelvis_tx',
       'pelvis_ty', 'pelvis_tz', 'hip_flexion_r', 'hip_adduction_r',
       'hip_rotation_r', 'knee_angle_r', 'knee_angle_r_beta', 'ankle_angle_r',
       'subtalar_angle_r', 'mtp_angle_r', 'hip_flexion_l', 'hip_adduction_l',
       'hip_rotation_l', 'knee_angle_l', 'knee_angle_l_beta', 'ankle_angle_l',
       'subtalar_angle_l', 'mtp_angle_l', 'lumbar_extension', 'lumbar_bending',
       'lumbar_rotation', 'arm_flex_r', 'arm_add_r', 'arm_rot_r',
       'elbow_flex_r', 'pro_sup_r', 'wrist_flex_r', 'wrist_dev_r',
       'arm_flex_l', 'arm_add_l', 'arm_rot_l', 'elbow_flex_l', 'pro_sup_l',
       'wrist_flex_l', 'wrist_dev_l'],
      dtype='object')

In [54]:
print(len(df_csv02))
print(len(df_npose02))
print(len(df_raw02))
print(len(df_sto02))
print(len(df_oerr02))
print(len(df_mot02))

1116
14
72670
1865
1817
1865

In [55]:
csv_path = os.path.join(dpath, 'S40', 'S40_A05_T01.csv')
print(csv_path)

df_csv05 = pd.read_csv(csv_path)
print(f'Length: {len(df_csv05)}')
print(f'Colunmn number: {len(df_csv05.columns)}')
df_csv05.head(2)

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A05_T01.csv
Length: 754
Colunmn number: 102

,pelvis_x,pelvis_y,pelvis_z,left_hip_x,left_hip_y,left_hip_z,right_hip_x,right_hip_y,right_hip_z,torso_x,...,left_index_knuckle_z,right_index_knuckle_x,right_index_knuckle_y,right_index_knuckle_z,left_thumb_tip_x,left_thumb_tip_y,left_thumb_tip_z,right_thumb_tip_x,right_thumb_tip_y,right_thumb_tip_z
0,12.6,471.8,6270.2,96.2,454.9,6324.1,-76.2,456.0,6213.0,16.8,...,6268.2,12.5,493.9,6011.8,244.5,529.3,6249.8,31.5,499.8,6015.1
1,20.7,470.3,6303.6,107.8,454.1,6357.1,-70.8,457.9,6247.1,19.9,...,6303.6,16.1,494.4,6040.4,255.6,528.9,6284.4,38.3,499.1,6044.3

In [56]:
csv_path = os.path.join(dpath, 'S40', 'S40_A05_T01_Npose.csv')
print(csv_path)

df_npose05 = pd.read_csv(csv_path)
print(f'Length: {len(df_npose02)}')
df_npose05.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A05_T01_Npose.csv
Length: 14

,pelvis_x,pelvis_y,pelvis_z,left_hip_x,left_hip_y,left_hip_z,right_hip_x,right_hip_y,right_hip_z,torso_x,...,left_index_knuckle_z,right_index_knuckle_x,right_index_knuckle_y,right_index_knuckle_z,left_thumb_tip_x,left_thumb_tip_y,left_thumb_tip_z,right_thumb_tip_x,right_thumb_tip_y,right_thumb_tip_z
0,-711.5,185.8,3931.5,-606.6,179.4,3924.4,-820.3,174.3,3945.1,-704.5,...,3833.6,-897.4,246.7,3882.6,-497.6,200.3,3826.7,-878.0,265.3,3873.7
1,-719.5,170.0,3972.6,-612.7,161.4,3965.5,-830.9,162.4,3985.5,-714.2,...,3869.3,-911.1,251.0,3923.3,-502.3,197.7,3862.7,-888.6,269.7,3913.9
2,-723.0,155.6,3987.7,-614.7,145.8,3980.6,-836.6,150.6,3999.9,-719.8,...,3881.5,-919.8,256.4,3938.4,-504.0,194.3,3875.2,-894.0,275.4,3928.9
3,-723.7,148.0,3987.6,-614.2,137.7,3980.7,-838.8,143.8,3999.1,-722.2,...,3876.5,-924.0,260.6,3938.2,-503.4,189.8,3870.6,-896.1,280.0,3928.5
4,-723.7,143.9,3983.6,-613.2,133.4,3976.7,-839.8,139.6,3994.5,-723.4,...,3868.6,-925.7,263.3,3934.0,-502.3,187.4,3863.0,-896.7,282.8,3924.2

In [57]:
csv_path = os.path.join(dpath, 'S40', 'S40_A05_T01.raw')
print(csv_path)

df_raw05 = pd.read_csv(csv_path)
print(f'Length: {len(df_raw05)}')
print(f'Length / numimus: {len(df_raw05)/5}')
df_raw05.head(10)

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/S40_A05_T01.raw
Length: 44335
Length / numimus: 8867.0

     QUAT       w       x       y       z     timestamp
0  qsBACK  0.6456 -0.0071 -0.7635 -0.0168  0.000000e+00
1   qsRUA  0.6584  0.4853 -0.3032  0.4889  0.000000e+00
2   qsRLA  0.4160  0.4158 -0.6398  0.4947  0.000000e+00
3   qsLUA  0.5781 -0.4395 -0.4155 -0.5478  0.000000e+00
4   qsLLA  0.3640 -0.4707 -0.6678 -0.4472  0.000000e+00
5  qsBACK  0.6943  0.2496 -0.6417  0.2093  1.663347e+09
6   qsRUA  0.4361  0.5344 -0.1842  0.7003  1.663347e+09
7   qsRLA  0.4567 -0.3427  0.2197 -0.7911  1.663347e+09
8   qsLUA  0.7645 -0.1482 -0.5343 -0.3287  1.663347e+09
9   qsLLA  0.1862 -0.1797 -0.5432 -0.7987  1.663347e+09

In [58]:
csv_path = os.path.join(dpath, 'S40', 'S40_A05_T01.sto')

# Open the file and skip the header (everything before 'endheader')
with open(csv_path, 'r') as file:
    # Read all lines
    lines = file.readlines()

# Find the line where the data starts (after 'endheader')
for i, line in enumerate(lines):
    if 'endheader' in line:
        start_idx = i + 1  # Data starts after the 'endheader'
        break

# Now read the data from the relevant lines and load it into a pandas DataFrame
from io import StringIO

# Join the data lines into a single string for pandas to read
data = ''.join(lines[start_idx:])

# Use StringIO to treat the string as a file and read it with pandas
df_sto05 = pd.read_csv(StringIO(data), sep='\s+')

# Display the DataFrame
print(f'Length: {len(df_sto05)}')
df_sto05.head()

Length: 1221

,time,torso_imu,humerus_r_imu,radius_r_imu,humerus_l_imu,radius_l_imu
0,0.00,"0.6455792578716615,-0.0070997718879937995,-0.7...","0.6584131354730802,0.4853096820247355,-0.30320...","0.41599630388925984,0.4157963056662362,-0.6397...","0.5780754467668368,-0.4394813334267857,-0.4154...","0.36400015106009403,-0.47070019534062163,-0.66..."
1,0.02,"0.6942723060300576,0.2497900360741875,-0.64167...","0.43607464299674314,0.5343689273502855,-0.1841...","0.4566713493382855,-0.34267850102524733,0.2196...","0.7644920072778456,-0.14809845163878216,-0.534...","0.18631259608885228,-0.17951213632822857,-0.54..."
2,0.04,"0.6942205041053876,0.24980737816987297,-0.6417...","0.4360899089962573,0.5342876367271274,-0.18429...","0.4568018386311007,-0.34250137857082313,0.2195...","0.7643731365781641,-0.14819479178556244,-0.534...","0.18629903217904173,-0.17929906854375835,-0.54..."
3,0.06,"0.6942059632548366,0.2498021458096488,-0.64170...","0.43609794380304245,0.5342974807933171,-0.1841...","0.4568018386311007,-0.34250137857082313,0.2195...","0.7643566906162672,-0.14821099247590058,-0.534...","0.18630570942594937,-0.17910548877180643,-0.54..."
4,0.08,"0.6941614161099985,0.2497861160246004,-0.64176...","0.43609794380304245,0.5342974807933171,-0.1841...","0.4567122286336347,-0.3424091681282166,0.21940...","0.7643849532302921,-0.14789708867446388,-0.534...","0.18629891853791683,-0.17899896091404782,-0.54..."

In [59]:
csv_path = os.path.join(dpath, 'S40', 'ik_S40_A05_T01_orientationErrors.sto')

data = []
columns = []
metadata_section = True  # Flag to skip metadata

with open(csv_path, 'r') as file:
    for line in file:
        line = line.strip()
        # Skip metadata section
        if metadata_section:
            if "endheader" in line:  # When the metadata ends
                metadata_section = False  # Switch to data reading mode
            continue
        
        # If we reach here, we're in the data section
        if line.startswith("time"):
            columns = line.split()  # Set column names when 'time' line appears
        else:
            data.append(line.split())  # Append numeric data

# Convert the data to a DataFrame
df = pd.DataFrame(data, columns=columns)

# Convert the values to appropriate data types
df_oerr05 = df.apply(pd.to_numeric)

# Display the first few rows
df_oerr05.head()

,time,torso_imu,humerus_r_imu,radius_r_imu,humerus_l_imu,radius_l_imu
0,0.00,7.100641e-17,1.321240e-16,1.079578e-16,1.228506e-16,1.758500e-16
1,0.02,3.820683e-05,1.935781e-02,7.689639e-02,5.672378e-03,2.357523e-02
2,0.04,1.473253e-04,1.925560e-02,7.682906e-02,5.818319e-03,2.305298e-02
3,0.06,5.024905e-05,1.925165e-02,7.693074e-02,5.758949e-03,2.293351e-02
4,0.08,1.531496e-04,1.939577e-02,7.713551e-02,5.791550e-03,2.353777e-02

In [60]:
# Define the file path
csv_path = os.path.join(dpath, 'S40', 'ik_S40_A05_T01.mot')
print(csv_path)

# Open the file and skip the header (everything before 'endheader')
with open(csv_path, 'r') as file:
    # Read all lines
    lines = file.readlines()

# Find the line where the data starts (after 'endheader')
for i, line in enumerate(lines):
    if 'endheader' in line:
        start_idx = i + 1  # Data starts after the 'endheader'
        break

# Now read the data from the relevant lines and load it into a pandas DataFrame
from io import StringIO

# Join the data lines into a single string for pandas to read
data = ''.join(lines[start_idx:])

# Use StringIO to treat the string as a file and read it with pandas
df_mot05 = pd.read_csv(StringIO(data), sep='\s+')

# Display the DataFrame
print(f'Length: {len(df_mot05)}')
df_mot05.head()

/Volumes/Data_Drive/datasets/VIDIMU/dataset/videoandimus/S40/ik_S40_A05_T01.mot
Length: 1221

,time,pelvis_tilt,pelvis_list,pelvis_rotation,pelvis_tx,pelvis_ty,pelvis_tz,hip_flexion_r,hip_adduction_r,hip_rotation_r,...,pro_sup_r,wrist_flex_r,wrist_dev_r,arm_flex_l,arm_add_l,arm_rot_l,elbow_flex_l,pro_sup_l,wrist_flex_l,wrist_dev_l
0,0.00,0.000000,0.000000,0.000000,0,0.94,0,0.000000,0.000000,0.000000,...,90.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,90.000000,0,0.0
1,0.02,-11.342020,0.230902,31.682974,0,0.94,0,2.919370,-1.388735,-0.984301,...,160.100219,0,0.0,21.372999,-4.507251,-7.566064,50.436207,139.033329,0,0.0
2,0.04,-11.265115,0.196738,31.742971,0,0.94,0,3.759283,-1.747479,-1.281896,...,160.099772,0,0.0,21.363263,-4.499129,-7.538066,50.455259,138.992173,0,0.0
3,0.06,-11.077876,0.101212,31.919757,0,0.94,0,5.544434,-2.390539,-1.900034,...,160.086891,0,0.0,21.370307,-4.486569,-7.545677,50.461385,139.000695,0,0.0
4,0.08,-11.042350,0.089377,31.956466,0,0.94,0,5.826366,-2.513949,-2.000263,...,160.079917,0,0.0,21.368613,-4.487098,-7.596597,50.444975,139.037762,0,0.0

In [61]:
print(len(df_csv05))
print(len(df_npose05))
print(len(df_raw05))
print(len(df_sto05))
print(len(df_oerr05))
print(len(df_mot05))

754
8
44335
1221
1221
1221